version: '3.1'

services:
  api:
    image: url-short:latest
    env_file:
      - .env
    ports:
      - 5001:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGUSER: url-short
      POSTGRES_PASSWORD: password
    volumes:
      -  pgdata:/var/lib/postgresql/data
    ports:
      - 5002:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
