name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.3'
      - run: test -z $(gofmt -l .)
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.3'
          cache: true
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest
  # TODO: Move to use compose based tests
  unit-test:
    needs: [fmt, lint]
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.3'
      - run: go test ./...
